### ISSUE TITLE
Doesnt work on mobile

### ISSUE THREAD

**Issue by icedtrees** [icedtrees/drawn-together#111]
You can add dots but not draw lines

**Comment by cloudier** [comment]
We probably need to add handlers for events like `touchmove`.
* [How can I make canvas drawing work on mobile
](https://stackoverflow.com/questions/43958030/how-can-i-make-canvas-drawing-work-on-mobile)
* [html5 canvas support on mobile](https://stackoverflow.com/questions/17656292/html5-canvas-support-in-mobile-phone-browser)

**Comment by cloudier** [comment]
@aluu4445 This was the easier issue I was talking about.
Most of the info you need is in the first link in the previous comment https://github.com/icedtrees/drawn-together/issues/111#issuecomment-602096537 and [this blog post](https://github.com/icedtrees/drawn-together/issues/111#issuecomment-602096537). In https://github.com/icedtrees/drawn-together/blob/c9aa13a0930f38793a9baf5e6caa3c20badfb4fe/modules/game/client/directives/drawing.client.directives.js we need to:

1. Turn off the default listeners for `touchstart`, `touchmove` and `touchend` (so that touching the canvas doesn't cause resizes and similar gestures) using code like:
```
document.body.addEventListener("touchend", function (e) {
  if (e.target == canvas) {
    e.preventDefault();
  }
}, false);
```

0. Add listeners for `touchstart`, `touchmove` and `touchend` that call the listeners for `mousestart`, `mousemove` and `mouseend` respectively.
